### ISSUE TITLE
Could you please provide all the codes or datasets?

### ISSUE THREAD

**Issue by DavisMeee** [ReedOnePeck/MindDiffuser#1]
Congratulations for your amazing work on Minddiffuser. When I tried to run this project, it seems lost some necessary .yaml and .json files. It also don't have the format about the dataset. Could you please help me out? Thank you very much!

**Comment by ReedOnePeck** [comment]
Hello, thank you for pointing out these issues. I will promptly improve the organization of the code and dataset folders.
As for the .yaml file you mentioned, I believe it is related to the Stable Diffusion(https://github.com/CompVis/stable-diffusion) pre-trained model. To ensure smooth code execution, I recommend that you first set up a virtual environment for Stable Diffusion. After successfully running Stable Diffusion V1-5, you can then run the MindDiffuser code within that virtual environment.

**Comment by ReedOnePeck** [comment]
The .json file you mentioned is likely related to lines 44 and 45 in MindDiffuser/Feature extractor/Semantic_feature_extraction.py. You should download it from the COCO dataset's official website.(https://cocodataset.org/#download)
