### ISSUE TITLE
A issue about data

### ISSUE THREAD

**Issue by songqianyi01** [ReedOnePeck/MindDiffuser#10]
Could you please upload mri data processed by four subjects v0.npy,v1.npy, etc., and preprocessed and divided into cocoid_trn_data and cocoid_val_data for four subjects? I process it by myself using the processed code, but the accuracy rate is about 0.04 in the feature decoding stage. I suspect that there is something wrong with the data I processed, which has really been bothering me for a long time, I would really appreciate it if you could.

**Comment by Zuskd** [comment]
How about add me on WeChat (lyz18391610168)? It will be more convenient for us to chat on it.
