### ISSUE TITLE
Specific ROI data extraction code

### ISSUE THREAD

**Issue by yinxu1996** [ReedOnePeck/MindDiffuser#12]
Hello athor. I can't find the relevant code to obtain these ROI files ("V0.npy", "V1.npy", etc.) in your code, could you tell me which specific code these ROI files come from? Looking forward to your reply. [yinxu1996@gmail.com](mailto:yinxu1996@gmail.com)

![316280760-84725721-5a67-489a-a7c9-08bd85056244](https://github.com/ReedOnePeck/MindDiffuser/assets/55089068/a3bf036c-1206-41e7-94cb-99b62d6e87b8)

**Comment by ReedOnePeck** [comment]
Utilize the code from this link (https://github.com/styvesg/nsd/blob/master/mask_preparation.ipynb) to acquire the mask files for each brain area, which match the full brain's 3D volume in shape but are composed solely of 0 and 1 at each location, with '1' signifying the selection of the voxel at that position. Subsequently, employ these mask files along with the pre-processed full-brain fMRI data to extract the voxels for each brain area.

**Comment by yinxu1996** [comment]
Thank you for your response. The number of voxels I obtained using this command is inconsistent with the author's paper. Did I select the wrong mask?
![image](https://github.com/ReedOnePeck/MindDiffuser/assets/55089068/0d6edfac-8175-46e2-8bf6-1730661e1401)
