### ISSUE TITLE
Some suggestions to help you replicate this work

### ISSUE THREAD

**Issue by ReedOnePeck** [ReedOnePeck/MindDiffuser#2]
1.I will standardize the organization of code and datasets on the server and update their folder structures on GitHub within a week.

2.Our work is based on Stable Diffusion v1-5. Therefore, I recommend that you first successfully run Stable Diffusion v1-5. Then you can run MindDiffuser in the virtual environment of Stable Diffusion, which should help avoid some environment-related errors.

3.Indeed, there are some three files in the code. 
(1) the .json file referenced on line 44 of MindDiffuser/Feature extractor/Semantic_feature_extraction.py needs to be downloaded from COCO2017 (https://cocodataset.org/#download). (2)The --stable_diffusion_config_path and (3)--stable_diffusion_skpt_path need to be downloaded from Stable Diffusion (https://github.com/CompVis/stable-diffusion).

4.If you encounter any other issues, feel free to continue the discussion with us.

**Comment by woctheyoung** [comment]
Not Stable Diffusion v1-4？or v1-5?

**Comment by ReedOnePeck** [comment]
Apologies for the late reply. We are using Stable Diffusion v1-4. Additionally, I just remembered a few important notes, so I will create a new issue and update a revised version of the reproduction instructions there.

**Comment by woctheyoung** [comment]
> Apologies for the late reply. We are using Stable Diffusion v1-4. Additionally, I just remembered a few important notes, so I will create a new issue and update a revised version of the reproduction instructions there.

OK,thanks
