### ISSUE TITLE
About data_preparation.ipynb in nsd.

### ISSUE THREAD

**Issue by zhangdanfeng888** [ReedOnePeck/MindDiffuser#5]
Hello, I don't understand this part:

"Run the code(https://github.com/styvesg/nsd/blob/master/data_preparation.ipynb) to obtain the textual descriptions of the stimulus images from NSD in the COCO dataset. Rename the corresponding file as "trn_cocoID_correct.npy" or "test_cocoID_correct.npy" and save it in the path "your_folder/data/utils_data/"."

The file(data_preparation.ipynb) has too much code, should I run all this code in sequence?
Or can you provide me the “trn_cocoID_correct.npy” and “test_cocoID_correct.npy” files?
Thanks  a lot.

**Comment by ReedOnePeck** [comment]
https://github.com/ReedOnePeck/MindDiffuser/tree/main/data/utils_data

**Comment by ReedOnePeck** [comment]
Download this file [cocoID.zip](https://github.com/ReedOnePeck/MindDiffuser/blob/main/data/utils_data/cocoID.zip)

**Comment by zhangdanfeng888** [comment]
> Download this file [cocoID.zip](https://github.com/ReedOnePeck/MindDiffuser/blob/main/data/utils_data/cocoID.zip)下载此文件 cocoID.zip

Thaks. I download the cocoID.zip then unzip it, it only contains four files: cocoId_correct_sub1.npy, cocoId_correct_sub2.npy, cocoId_correct_sub5.npy and cocoId_correct_sub7.npy, should I rename these four files to "trn_cocoID_correct_sub*.npy" or "test_cocoID_correct_sub*.npy”"?

**Comment by ReedOnePeck** [comment]
No, thanks for you reminder, I have revised the readMe

**Comment by zhangdanfeng888** [comment]
Okay, I'll try that in a minute. Thank you. By the way, there is a slight error here:
![image](https://github.com/ReedOnePeck/MindDiffuser/assets/41187774/5d05cbbc-9a93-45e8-b91a-66474186292d)
It should be "environment_1.yaml", haha.

**Comment by ReedOnePeck** [comment]
Thanks for your reminder

**Comment by zhangdanfeng888** [comment]
@ReedOnePeck I find another question when I run python Feature extractor/Structural_feature_extraction.py:

Traceback (most recent call last):
  File "Feature extractor/Structural_feature_extraction.py", line 113, in <module>
    main()
  File "Feature extractor/Structural_feature_extraction.py", line 89, in main
    stim_sub1_val_CLIP = CLIP_extraction(args.stim_sub1_val_multi, args.target_layers)
  File "Feature extractor/Structural_feature_extraction.py", line 59, in CLIP_extraction
    feature_maps = FE.get_all_feature_maps(model, stimulus_loader, layers_to_retain=target_layers,
  File "/data/zhangdf/sihuo/MindDiffuser/packages/feature_extraction_detach.py", line 230, in get_all_feature_maps
    feature_maps = get_empty_feature_maps(model, next(iter(inputs))[:3], input_size,
  File "/data/zhangdf/sihuo/MindDiffuser/packages/feature_extraction_detach.py", line 196, in get_empty_feature_maps
    empty_feature_maps = get_feature_maps(model, inputs, layers_to_retain, remove_duplicates)
  File "/data/zhangdf/sihuo/MindDiffuser/packages/feature_extraction_detach.py", line 169, in get_feature_maps
    model(inputs)
  File "/home/inspur/anaconda3/envs/MindDiffuser/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1128, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/data/zhangdf/sihuo/MindDiffuser/src/CLIP/clip/model.py", line 224, in forward
    x = self.conv1(x)  # shape = [*, width, grid, grid]
  File "/home/inspur/anaconda3/envs/MindDiffuser/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1128, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/inspur/anaconda3/envs/MindDiffuser/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/inspur/anaconda3/envs/MindDiffuser/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same

What should I do to solve this question?

**Comment by ReedOnePeck** [comment]
RuntimeError: Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same
As you can see from this, the incoming data is in a different format that causes the error, and you should use pycharm's debug to check the points where the error occurred by hitting the breakpoint.
Go to CSDN or Google to find a solution to the problem.

**Comment by zhangdanfeng888** [comment]
@ReedOnePeck Hello, sorry to trouble you again. When I run python Feature extractor/Structural_feature_selection.py, I get "cuda out of memory", could you share files from "index_save_path" in the code? Thanks a lot.
![image](https://github.com/ReedOnePeck/MindDiffuser/assets/41187774/0a6eb1ce-3946-4709-a974-8c5af97bec5d)

**Comment by ReedOnePeck** [comment]
Sorry for replying you so late. I have uploaded the required documents for participant 1.
![1705756950700](https://github.com/ReedOnePeck/MindDiffuser/assets/96508891/93409dab-0936-4c2e-8511-05e7e6d4ee5b)

**Comment by zhangdanfeng888** [comment]
> Sorry for replying you so late. I have uploaded the required documents for participant 1. ![1705756950700](https://private-user-images.githubusercontent.com/96508891/298284392-93409dab-0936-4c2e-8511-05e7e6d4ee5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2Njk5MjgsIm5iZiI6MTcwNjY2OTYyOCwicGF0aCI6Ii85NjUwODg5MS8yOTgyODQzOTItOTM0MDlkYWItMDkzNi00YzJlLTg1MTEtMDVlN2U2ZDRlZTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDAyNTM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNGQ4MTUyM2RkYTFhN2I1NmUyYTBjZjAzNzgxYzM1ZjQ4Y2Y5ZDI2NDI2NzIzYzYyZDM1OGFmYTk1NDMyYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gVw3zc8JgeOs4OlyQhdyXf3iudjEZILCOpqDQqqYmYg)

Thanks for your reply. I want to run "python Feature decoding/Semantic_feature_decoding.py", but I don't know where is the file in the code. 
![image](https://github.com/ReedOnePeck/MindDiffuser/assets/41187774/fbce69b3-404d-4b54-872c-915544e41669)
Could you tell me where are these files? Are they root in "Feature extractor"?
By the way, I modify the "ROIs" to ["nsd_train_fmriavg_nsdgeneral_sub1"], am I right?
![image](https://github.com/ReedOnePeck/MindDiffuser/assets/41187774/a183107d-9037-4dd7-bda5-4e2c6f2ec8c1)

**Comment by ReedOnePeck** [comment]
1.
（1）'trn_file_ex'  and 'val_file_ex' refer to the folders where the preprocessed fMRI data are stored
（2）The other four file names refer to the path where you save the semantic features. You should run the files in "Feature extractor" to save the features first.
（3）You don't need to pay attention to recons_img_idx, it seems to be a mistake I made when organizing the code.

2.
ROI refers to different brain region numbers, such as V1, V2, IT, etc. It depends on the format of your preprocessed fMRI data. For specific ROI entries, you can refer to line 21of MindDiffuser/Feature decoding /Semantic_feature_decoding.py
