### ISSUE TITLE
metrics

### ISSUE THREAD

**Issue by xiaRunZe** [ReedOnePeck/MindDiffuser#6]
Dear author, could you kindly guide us to the section of the code where the implementation for the three evaluation metrics (PCC, SSIM, CLIP Similarity) can be located?

**Comment by ReedOnePeck** [comment]
Sure.
1.PCC
![1705391284324](https://github.com/ReedOnePeck/MindDiffuser/assets/96508891/ccf714c9-6de9-4589-80c7-034193c937ee)
2.SSIM
![1705391319708](https://github.com/ReedOnePeck/MindDiffuser/assets/96508891/73b027cb-bd5c-4fb7-b955-7214320cfdd7)
3.CLIP Similarity
![1705391388950](https://github.com/ReedOnePeck/MindDiffuser/assets/96508891/5b12b540-8d92-4073-ba3d-1a8de03c72be)

If you have any other questions, please feel free to contact us.
